(defpackage :logos.media.stream (:use :cl))
(in-package :logos.media.stream)
(defun MediaStream ()
  (defun publish ())
  (defun unpublish ())
  `((:publish ,#'publish)
    (:unpublish ,#'unpublish)))
(defun GUI ()
  (defun run ())
  (defun stop ())
  `((:run ,#'run)
    (:stop ,#'stop)))
(defun MediaStreamProtocol ())
(defun WindowCapture ())
(defun WindowSelectionWidget ())
(defun PreviewWidget (stream))
(defun VideoCapture ())
